import { Component } from '@angular/core';

@Component({
  selector: 'app-user-review',
  templateUrl: './user-review.component.html',
  styleUrl: './user-review.component.css',
})
export class UserReviewComponent {
  reviewsRow1 = [
    {
      name: 'Priya Sharma',
      role: 'SDE-2, Google India',
      initials: 'PS',
      avatarBg: 'linear-gradient(135deg, #6366f1, #06b6d4)',
      quote: 'Cracked Google in 6 weeks using InterviewPrepHub. The domain questions were exactly what I needed!',
      tag: 'Hired at Google',
      tagBg: 'rgba(16,185,129,0.12)',
      tagColor: '#34d399',
      companyIcon: 'fa-google',
      companyColor: '#4285F4',
    },
    {
      name: 'Rahul Mehta',
      role: 'Backend Eng, Microsoft',
      initials: 'RM',
      avatarBg: 'linear-gradient(135deg, #f59e0b, #ef4444)',
      quote: 'Mock interview scorer jumped from 45 to 87 in just a month. The feedback loop is incredible.',
      tag: 'Score +42pts',
      tagBg: 'rgba(99,102,241,0.12)',
      tagColor: '#818cf8',
      companyIcon: 'fa-microsoft',
      companyColor: '#00A4EF',
    },
    {
      name: 'Anjali Singh',
      role: 'VLSI Engineer, Qualcomm',
      initials: 'AS',
      avatarBg: 'linear-gradient(135deg, #10b981, #06b6d4)',
      quote: "Best platform for ECE students. Company-specific prep is brilliant. Landed my Qualcomm offer!",
      tag: 'Hired at Qualcomm',
      tagBg: 'rgba(16,185,129,0.12)',
      tagColor: '#34d399',
      companyIcon: 'fa-microchip',
      companyColor: '#e23237',
    },
    {
      name: 'Dev Patel',
      role: 'Full Stack, Razorpay',
      initials: 'DP',
      avatarBg: 'linear-gradient(135deg, #8b5cf6, #f59e0b)',
      quote: "The activity timeline keeps me accountable. Haven't missed a practice day in 3 months!",
      tag: '90-Day Streak',
      tagBg: 'rgba(245,158,11,0.12)',
      tagColor: '#fbbf24',
      companyIcon: 'fa-rupee-sign',
      companyColor: '#2EB8E6',
    },
  ];

  reviewsRow2 = [
    {
      name: 'Sneha Nair',
      role: 'Data Scientist, Amazon',
      initials: 'SN',
      avatarBg: 'linear-gradient(135deg, #ef4444, #8b5cf6)',
      quote: "The ML & DSA question bank is phenomenal. Prepared me perfectly for Amazon's data science rounds.",
      tag: 'Hired at Amazon',
      tagBg: 'rgba(16,185,129,0.12)',
      tagColor: '#34d399',
      companyIcon: 'fa-amazon',
      companyColor: '#FF9900',
    },
    {
      name: 'Karan Joshi',
      role: 'Systems Eng, Intel',
      initials: 'KJ',
      avatarBg: 'linear-gradient(135deg, #06b6d4, #6366f1)',
      quote: 'For mechanical-electrical interdisciplinary roles, this is the only platform that covers all bases.',
      tag: 'Hired at Intel',
      tagBg: 'rgba(99,102,241,0.12)',
      tagColor: '#818cf8',
      companyIcon: 'fa-microchip',
      companyColor: '#0071C5',
    },
    {
      name: 'Meera Rao',
      role: 'CS Grad, IIT Bombay',
      initials: 'MR',
      avatarBg: 'linear-gradient(135deg, #10b981, #f59e0b)',
      quote: "Used it for campus placements. The system design section gave me a huge edge in technical rounds.",
      tag: 'Campus Placement',
      tagBg: 'rgba(6,182,212,0.12)',
      tagColor: '#22d3ee',
      companyIcon: 'fa-university',
      companyColor: '#f59e0b',
    },
    {
      name: 'Arjun Kumar',
      role: 'DevOps, Flipkart',
      initials: 'AK',
      avatarBg: 'linear-gradient(135deg, #f59e0b, #10b981)',
      quote: 'Networks & OS questions helped me clear Flipkart backend round. Extremely well structured content.',
      tag: 'Hired at Flipkart',
      tagBg: 'rgba(16,185,129,0.12)',
      tagColor: '#34d399',
      companyIcon: 'fa-shopping-cart',
      companyColor: '#F7941D',
    },
  ];

  reviewStats = [
    { value: '50K+', label: 'Happy Users' },
    { value: '4.9/5', label: 'Avg Rating' },
    { value: '95%', label: 'Got Hired' },
    { value: '200+', label: 'Companies' },
  ];
}
